server.port=8080

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://wellnest:wellnest@cluster0.tbfetlf.mongodb.net/wellnest


# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vd98847@gmail.com
spring.mail.password=zhzxxnlshjdahmpl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=9f8a7c6b5e4d3c2a1f0e9d8c7b6a5f4e1234567890abcdef1234567890abcdef

jwt.expiration=86400000

# CORS Configuration
cors.allowed-origins=http://localhost:3000
